name: Publish Docker image

on: push

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
        
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
      
      - name: Log in
        uses: docker/login-action@v1.12.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v3.6.2
        with:
          images: webwatcher/certificate-MVC
      
      - name: Build and push
        uses: docker/build-push-action@v2.7.0
        with:     
          context: .
          file: ./src/Web/Dockerfile
          push: true
          tags: webwatcher/certificate-mvc:dev
          labels: ${{ steps.meta.outputs.labels }}
